const items = [
    {
        id: '01',
        image: 'images/9.jpg',
        company: 'Plum',
        item_name: 'Niacinamide Serum',
        original_price: 649,
        current_price: 584,
        discount_percentage: 10,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.5,
            count: 657,
        },
    },
    {
        id: '02',
        image: 'images/2.jpg',
        company: 'Minimalist',
        item_name: 'Cleanser Salicyclic Acid + LHA',
        original_price: 299,
        current_price: 284,
        discount_percentage: 5,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.3,
            count: 355,
        },
    },
    {
        id: '03',
        image: 'images/3.jpg',
        company: 'Aqualogica',
        item_name: 'Vitamin C Sunscreen',
        original_price: 399,
        current_price: 351,
        discount_percentage: 12,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.3,
            count: 856,
        },
    },
    {
        id: '04',
        image: 'images/4.jpg',
        company: 'Plum',
        item_name: 'GreenTea Face Mist',
        original_price: 360,
        current_price: 324,
        discount_percentage:10,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.1,
            count: 344,
        },
    },
    {
        id: '05',
        image: 'images/5.jpg',
        company: 'Loreal',
        item_name: 'Revitalift Hyaluronic Acid Cream',
        original_price: 999,
        current_price: 749,
        discount_percentage: 42,
        return_period: 25,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.2,
            count: 350,
        },
    },
    {
        id: '06',
        image: 'images/6.jpg',
        company: 'mCaffeine',
        item_name: 'Under Eye Patch',
        original_price: 799,
        current_price: 649,
        discount_percentage: 19,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 3.9,
            count: 212,
        },
    },
    {
        id: '07',
        image: 'images/7.jpg',
        company: 'Plum',
        item_name: 'Vitamin C Serum',
        original_price: 790,
        current_price: 695,
        discount_percentage: 12,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.7,
            count: 889,
        },
    },
    {
        id: '08',
        image: 'images/8.jpg',
        company: 'NYKKA',
        item_name: 'Face Scrub',
        original_price: 249,
        current_price: 125,
        discount_percentage: 50,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.2,
            count: 520,
        },
    }
];

//haircare Products Start 

const haircareItems = [
    {
        id: '09',
        image: 'images/exclus.jpg.png',
        company: 'NYVEDA',
        item_name: 'HairCare Kit',
        original_price: 1848,
        current_price: 1571,
        discount_percentage: 15,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 3.5,
            count: 115,
        },
    },
    // Add more haircare products as needed
    {
        id: '10',
        image: 'images/11.jpg',
        company: 'Pilgrim',
        item_name: 'Hair Growth Serum',
        original_price: 895,
        current_price: 761,
        discount_percentage: 15,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.9,
            count: 1200,
        },
    },
    {
        id: '11',
        image: 'images/12.jpg',
        company: 'Love Beauty',
        item_name: 'Hair Mask',
        original_price: 600,
        current_price: 480,
        discount_percentage: 20,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.7,
            count: 899,
        },
    },
    {
        id: '12',
        image: 'images/13.jpg',
        company: 'Biolage',
        item_name: 'Hair Serum',
        original_price: 650,
        current_price: 585,
        discount_percentage: 10,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.9,
            count: 1589,
        },
    },
    {
        id: '13',
        image: 'images/14.jpg',
        company: 'NYKKA',
        item_name: 'Scalp Massager',
        original_price: 499,
        current_price: 284,
        discount_percentage: 43,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 3.2,
            count: 890,
        },
    },
    {
        id: '14',
        image: 'images/15.jpg',
        company: 'BBLUNT',
        item_name: 'Intense Moisture Conditioner',
        original_price: 399,
        current_price: 355,
        discount_percentage: 11,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.2,
            count: 459,
        },
    },
    {
        id: '15',
        image: 'images/16.jpg',
        company: 'mCaffeine',
        item_name: 'Scalp Scrub',
        original_price: 599,
        current_price: 509,
        discount_percentage: 15,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.4,
            count: 789,
        },
    },
    {
        id: '16',
        image: 'images/17.jpg',
        company: 'NYKKA',
        item_name: 'Hair Oil',
        original_price: 599,
        current_price: 509,
        discount_percentage: 15,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.7,
            count: 1250,
        },
    },
];

